version: '3.9'

services:
  db:
    image: mongo:latest
    restart: always
    env_file:
      - .env
    ports:
      - "${MONGODB_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
    volumes:
      - todo_db_volume:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    env_file:
      - .env
    ports:
      - "${MONGO_EXPRESS_PORT}:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: "db"
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${ME_CONFIG_MONGODB_ADMINUSERNAME}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${ME_CONFIG_MONGODB_ADMINPASSWORD}"
    depends_on:
      - db
      
  # app:
  #   build: .
  #   env_file:
  #     - .env
  #   ports:
  #     - "${PORT}:8000"
  #   depends_on:
  #     - db

volumes:
  todo_db_volume: